### ISSUE TITLE
Tmux with `-u` to support unicode characters?

### ISSUE THREAD

**Issue by hurui200320** [desertwitch/TTM-unRAID#1]
Hi, thank you for making this plugin. Today I was trying to run a checksum script on my files using this plugin, and I noticed that some of the unicode characters cannot be displayed properly.

For example, with unraid's terminal:
```
root@unraid:~# echo 中文
中文
```
This is how it works. If I tried to type the same thing in the tmux:
```
echo ____
```

Even with copy and paste, I can't get any non-ascii character working. It will become underscore. However, it might only be a display issue since if I tried `echo 中文 > test`, the Chinese will become `_`, but if I then `cat test` in a normal terminal, the text looks fine.

One solution I found is using `tmux -u` when starting tmux. I tried in a unraid terminal and that does work perfectly. So I would like to ask if you can launch tmux with `-u` so it can properly handle the unicode characters.

Thanks.

**Comment by desertwitch** [comment]
Hey! Thanks for letting me know, will be included in the next update.

**Comment by desertwitch** [comment]
It's been included in today's update, please let me know if it works for you now.

**Comment by hurui200320** [comment]
Hi, thank you for fixing the issue. I tested the new version and it works perfectly. Thanks :)

I'll close this ticket now.
